### ISSUE TITLE
FetchError: request to https://home.cielowigle.com/home/index failed

### ISSUE THREAD

**Issue by lvnilesh** [nicholasrobinson/node-smartcielo#12]
I run these:
```
cd /homebridge/node_modules/homebridge-smartcielo/node_modules/node-smartcielo

node index.js -u email@address.com -p password -i 192.168.0.22 --verbose
```

This is the result I get.
```
Connecting...
(node:9795) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

Communication Error: FetchError: request to https://home.cielowigle.com/home/index failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-smartcielo/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:375:28)
    at onerror (/homebridge/node_modules/homebridge-smartcielo/node_modules/agent-base/dist/src/index.js:117:21)
    at callbackError (/homebridge/node_modules/homebridge-smartcielo/node_modules/agent-base/dist/src/index.js:136:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
```

**Comment by lvnilesh** [comment]
Issue #10  seems related

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/node-smartcielo/issues/19
