### ISSUE TITLE
TypeError: Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by rsteenbu** [nicholasrobinson/node-smartcielo#18]
Hi Nicholas,

I'm just trying to get this working for the first time and I can't seem to get around this.
Here's the error I'm getting:
[8/6/2022, 8:47:14 AM] [SmartCielo] TypeError: Cannot read property 'getAttribute' of null
    at getAppUserAndSessionId (/usr/lib/node_modules/homebridge-smartcielo/node_modules/node-smartcielo/SmartCielo.js:127:64)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)

Here's my config:
`        {
          "accessory": "SmartCieloThermostat",
          "name": "SmartCielo",
          "username": "REDACTED",
          "password": "REDACTED",
          "ip": "REDACTED
        }`

Here's my node-smartcielo version:
`homebridge-smartcielo@0.0.8 /usr/lib/node_modules/homebridge-smartcielo
└── node-smartcielo@0.0.5`

Any help you can provide would be much appreciated!

Richard Steenburg

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/node-smartcielo/issues/19
