### ISSUE TITLE
Communication Error: TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by nicholasrobinson** [nicholasrobinson/node-smartcielo#8]
Attempting to run the demo script or instantiate the **node-smartcielo** class results in the following error output, e.g.:

```
$ node index.js -u XXX -p YYY -i ZZZ -v
Connecting...
Communication Error: TypeError: Cannot read property 'map' of undefined
    at getCookiesFromResponse (.../node-smartcielo/SmartCielo.js:28:24)
    at fetch.then.response (.../node-smartcielo/SmartCielo.js:110:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Connected.
(node:14075) UnhandledPromiseRejectionWarning: Error: Not Connected.
    at SmartCielo.getState (.../node-smartcielo/SmartCielo.js:374:19)
    at hvac.waitForConnection.then._ (.../node-smartcielo/index.js:47:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14075) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:14075) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The underlying issue is:

```
TypeError: Cannot read property 'map' of undefined
    at getCookiesFromResponse (.../node-smartcielo/SmartCielo.js:28:24)
    at fetch.then.response (.../node-smartcielo/SmartCielo.js:110:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Which suggests the login flow/API is changed.

This has been reported by multiple others (@vincentanthony @forevaclevah @sparky742) in [homebridge-smartcielo](https://github.com/nicholasrobinson/homebridge-smartcielo) here:

- https://github.com/nicholasrobinson/homebridge-smartcielo/issues/8

Once the issue is resolved in [node-smartcielo](https://github.com/nicholasrobinson/node-smartcielo), it will be resolved by a dependency bump in [homebridge-smartcielo](https://github.com/nicholasrobinson/homebridge-smartcielo) also.

Note: This is possibly resolved-by/related to @androolloyd 's PR:
https://github.com/nicholasrobinson/node-smartcielo/pull/7

**Comment by nicholasrobinson** [comment]
This particular error is resolved now.
